
# .goreleaser.yml
brews:
  - # GitHub/GitLab repository to push the formula to
    tap:
      owner: any_owner_name
      name: cli

    name: brew_installer_name
    # Template for the url which is determined by the given Token (github or gitlab)
    # Default for github is "https://github.com/<repo_owner>/<repo_name>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    url_template: "https://github.com/<repo_owner>/<repo_name>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    homepage: https://github.com/homepage

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: thycotic
      email: xyz@mail.com

    folder: Formula

    # Caveats for the user of your binary.
    # Default is empty.
    caveats: ""

    # Your app's description.
    # Default is empty.
    description: ""

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "MIT"

    # Packages your package depends on.
    dependencies:
      - name: git
      - name: go

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - "^*.md:"



