---
parameters:
  - name: clean
    displayName: Checkout clean
    type: boolean
    default: false
    values:
      - false
      - true

  # Bypass scans & tests on repeated runs that have already passed these, helping troubleshooting pipeline issues on a release more quickly
  - name: yolo
    displayName: you only live once
    type: boolean
    default: false
    values:
      - false
      - true

variables:
  - group: 'CLI_integration_test'
  - group: 'CLi-pipeline-variables'
  - group: 'CLI End-to-End tests'
  - template: templates/vars.go.yml
  - name: ARTIFACT_DOWNLOAD_DIRECTORY
    value: $(System.DefaultWorkingDirectory)/.artifacts/builds/
  - name: ARTIFACT_TEST_DIRECTORY
    value: $(System.DefaultWorkingDirectory)/.artifacts/test/
trigger:
  branches:
    include:
      - master
      - refs/tags/*
  paths:
    exclude:
      - .devcontainer/*
      - .github/*
      - '*.md'
      - '**/*.md'

schedules:
  - cron: '0 6 * * 1-5'
    displayName: 'Mon through Fri at 6:00'
    branches:
      include:
        - master

jobs:
  - job: Build_All_Platforms
    pool:
      vmImage: ubuntu-latest
      # name: DSV-Golang-AWS

    steps:
      - checkout: self
        clean: ${{ parameters.clean }}

      - task: Delinea.delinea-dsv-task.dsv-azure-pipelines-task.DelineaDSV@0
        displayName: 'Retrieve ado/cli from Thycotic DevOps Secrets Vault'
        inputs:
          ServerUrl: '$(ServerUrl)'
          ClientId: '$(ClientId)'
          ClientSecret: '$(ClientSecret)'
          SecretPath: ado/cli

      - template: templates/task-go-install.yml
      - template: templates/task-go-detect-vendoring.yml
      - template: templates/task-go-restore-go-cache.yml
      - template: templates/task-go-mod-download.yml
      - template: templates/task-go-install-mage.yml

      - task: WhiteSource@21
        condition: ne(${{ parameters.yolo }}, 'true')
        inputs:
          cwd: '$(System.DefaultWorkingDirectory)'
          scanReportTimeout: '3'
      - bash: |
          $(GOBIN)/mage init
        displayName: mage-init
        condition: ne(${{ parameters.yolo }}, 'true')
        env:
          MAGEFILE_HASHFAST: 1

      - bash: |
          echo "---- GIT STATUS -----"
          make status
          echo "[---] git describe: $(git describe --always --dirty --tags)"
          go test -v -p 1 -covermode=count -coverprofile=./coverage.out ./... | tee test.out
          rm -f cli-config/.thy.yml
          echo "[---] Merging coverage."
          $(GOBIN)/gocovmerge -dir coverage -pattern "\.out" > ./coverage-integration.out
          rm -rf coverage
          echo "[---] Finished."
        displayName: 'Run tests'
        condition: ne(${{ parameters.yolo }}, 'true')

      - bash: |
          cat test.out | $(GOBIN)/go-junit-report -set-exit-code > ./report.xml
        displayName: 'Generate report'
        condition: ne(${{ parameters.yolo }}, 'true')

      - bash: |
          echo "[---] git describe: $(git describe --always --dirty --tags)"

          echo "[---] Starting End-to-End testing."
          make e2e-test | tee test-e2e.out

          echo "[---] Merging E2E coverage results into one file."
          $(GOBIN)/gocovmerge -dir ./tests/e2e/coverage -pattern "\.out" > ./coverage-e2e.out
          rm -rf ./tests/e2e/coverage

          echo "[---] Finished."
        condition: and(always(), ne(${{ parameters.yolo }}, 'true'))
        displayName: '[E2E] Run tests'

      - bash: |
          cat test-e2e.out | $(GOBIN)/go-junit-report -set-exit-code > ./report-e2e.xml
        displayName: '[E2E] Generate report'
        condition: ne(${{ parameters.yolo }}, 'true')

      - bash: |
          echo "[---] Merging coverage.out, coverage-e2e.out and coverage-integration.out files."
          $(GOBIN)/gocovmerge coverage.out coverage-e2e.out coverage-integration.out > ./coverage-all.out

          echo "[---] Converting coverage-all.out to codecoverage.xml file."
          $(GOBIN)/gocov convert coverage-all.out | $(GOBIN)/gocov-xml > ./codecoverage.xml

          echo "[---] Finished."
        displayName: 'Prepare coverage'
        condition: ne(${{ parameters.yolo }}, 'true')

      - task: PublishTestResults@2
        displayName: 'Publish Test Results'
        inputs:
          testResultsFiles: |
            **/report.xml
            **/report-e2e.xml
          mergeTestResults: true
          failTaskOnFailedTests: true
          testRunTitle: 'CLI Tests'
        condition: and(succeededOrFailed(), ne(${{ parameters.yolo }}, 'true'))

      - task: PublishCodeCoverageResults@1
        displayName: 'Publish Code Coverage'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/codecoverage.xml'
          failIfCoverageEmpty: true
        condition: and(succeededOrFailed(), ne(${{ parameters.yolo }}, 'true'))

      - bash: |
          echo "[---] git describe: $(git describe --always --dirty --tags)"
          # clean build directory
          make clean build-release-all create-checksum capture-latest-version

          version=$(git describe --always --dirty --tags)
          echo "##vso[task.setvariable variable=CLI_VERSION;]$version"

          mkdir $(Build.ArtifactStagingDirectory)/version
          mv $(ARTIFACT_DOWNLOAD_DIRECTORY)bin/cli-version.json $(Build.ArtifactStagingDirectory)/version
        displayName: 'Make - Release Builds'

      - task: CopyFiles@2
        displayName: 'Copy Unsigned Builds To Staging Directory'
        inputs:
          SourceFolder: $(ARTIFACT_DOWNLOAD_DIRECTORY)bin
          TargetFolder: '$(Build.ArtifactStagingDirectory)/bin/'
          CleanTargetFolder: true
          OverWrite: true

      - task: PublishBuildArtifacts@1
        displayName: 'Build Artifact: Latest version file'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/version/cli-version.json'
          ArtifactName: 'cli-latest-version'

      - task: PublishPipelineArtifact@1
        displayName: 'Pipeline Artifact: Unsigned Builds'
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)/bin'
          artifact: 'ReleaseBuilds-Unsigned'

      - task: Bash@3
        displayName: 'Public GitHub Sync'
        inputs:
          filePath: pipelines/scripts/github_sync.sh
        env:
          SourceVersion: $(Build.SourceVersion)
          githubPat: $(githubPat)
        condition: and(succeeded(), or(startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')))

  - job: Sign_Windows_Binary
    dependsOn: Build_All_Platforms
    pool:
      vmImage: windows-latest
      # name: Bambe-Windows
    steps:
      - checkout: self
        clean: ${{ parameters.clean }}

      - template: templates/task-go-install.yml
      - template: templates/task-go-detect-vendoring.yml
      - template: templates/task-go-restore-go-cache.yml
      - template: templates/task-go-mod-download.yml
      - template: templates/task-go-install-mage.yml

      - pwsh: |
          Write-Host "[---] Deleting test cache."
          &go clean -testcache
          Write-Host "[---] Starting End-to-End testing."
          &go test -v -tags=endtoend ./tests/e2e
          Write-Host "[---] Finished."
          Write-Host "[---] Note: Results are not published."
        displayName: '[E2E] Run tests'
        condition: ne(${{ parameters.yolo }}, 'true')

      - task: Delinea.delinea-dsv-task.dsv-azure-pipelines-task.DelineaDSV@0
        displayName: 'Retrieve ado/cli from Thycotic DevOps Secrets Vault'
        inputs:
          ServerUrl: '$(ServerUrl)'
          ClientId: '$(ClientId)'
          ClientSecret: '$(ClientSecret)'
          SecretPath: 'ado/cli '
      - task: DownloadSecureFile@1
        name: signCert
        displayName: download-cert
        inputs:
          secureFile: $(certSecureFile)
      # NOTE: Disabled as using directly in SignTool.exe cli args. Leaving here in case need to revert back to installation for any other reason, and will remove later if not required - 2022-09
      # - pwsh: |
      #     Import-PfxCertificate -FilePath '$(signCert.secureFilePath)' -Password $('$(cert.password)' | ConvertTo-SecureString -AsPlainText -Force) -CertStoreLocation 'cert:\localmachine\root'
      #     Write-Host "Start adding the PFX file to the certificate store."
      #     $pfxpath = '$(signCert.secureFilePath)'
      #     $password = '$(cert.password)'
      #     Add-Type -AssemblyName System.Security
      #     $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2
      #     $cert.Import($pfxpath, $password, [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]"PersistKeySet")
      #     $store = new-object system.security.cryptography.X509Certificates.X509Store -argumentlist "MY", CurrentUser
      #     $store.Open([System.Security.Cryptography.X509Certificates.OpenFlags]"ReadWrite")
      #     $store.Add($cert)
      #     $store.Close()
      #   displayName: import-cert
      - pwsh: |
          # Clean out old builds from cli dir
          $CLIDirectory = Join-Path $ENV:SYSTEM_DEFAULTWORKINGDIRECTORY 'cli'
          $CoverageDirectory = Join-Path $ENV:SYSTEM_DEFAULTWORKINGDIRECTORY 'coverage'

          Remove-Item $CLIDirectory -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item $CoverageDirectory -Recurse -Force -ErrorAction SilentlyContinue
        workingDirectory: '$(Pipeline.Workspace)'
        displayName: 'Clear Pipeline Directory'

      - task: DownloadPipelineArtifact@2
        displayName: 'Download Unsigned Builds'
        inputs:
          artifactName: 'ReleaseBuilds-Unsigned'
          targetPath: $(ARTIFACT_DOWNLOAD_DIRECTORY)

      - pwsh: |
          Write-Host "---- GIT STATUS -----"
          &git status
          $version = &git describe --always --dirty --tags
          Write-Host "##vso[task.setvariable variable=CLI_VERSION]$version"
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        displayName: 'Get Version'

      - pwsh: |
          Remove-Item (Join-Path '$(CLI_VERSION)' '$(constants.cliname)-darwin-arm64') -ErrorAction SilentlyContinue
          Remove-Item (Join-Path '$(CLI_VERSION)' '$(constants.cliname)-darwin-arm64-sha256.txt') -ErrorAction SilentlyContinue
          Remove-Item (Join-Path '$(CLI_VERSION)' '$(constants.cliname)-darwin-x64') -ErrorAction SilentlyContinue
          Remove-Item (Join-Path '$(CLI_VERSION)' '$(constants.cliname)-darwin-x64-sha256.txt') -ErrorAction SilentlyContinue
          Write-Host (Get-ChildItem '$(CLI_VERSION)' -ErrorAction SilentlyContinue | Format-Table -Autosize -Wrap | Out-String)
        workingDirectory: $(ARTIFACT_DOWNLOAD_DIRECTORY)
        displayName: 'Clear Unused Files'
      - pwsh: |
          # Since MSBuild can't seem to access SignTool.exe from it's existing
          # path, make a local copy (if none already exists):
          $signToolPath = "C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool\SignTool.exe"
          Write-Host "SignTool exists: '$(test-path "$pathToCheck" -PathType Leaf)'"
          Write-Host "##vso[task.prependpath]C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool"
        displayName: find-signtool

      - pwsh: |
          $MageBinary = Join-Path $ENV:GOBIN 'mage'
          Write-Host "MageBinary: [$(Test-Path $MageBinary -PathType Leaf -Verbose)]"
          Invoke-Expression "$MageBinary sign"
        displayName: mage sign
        env:
          CLI_VERSION: $(CLI_VERSION)
          CLI_NAME: $(constants.cliname)
          CERT_PATH: $(signCert.secureFilePath)
          CERT_PASS: $(cert.password)
          MAGEFILE_HASHFAST: 1

      - pwsh: |
          $X64Version = Join-Path $(CLI_VERSION) $(constants.cliname)-win-x64.exe
          $X86Version = Join-Path $(CLI_VERSION) $(constants.cliname)-win-x86.exe

          Get-FileHash $X64Version -Algorithm SHA256 | Select -expand Hash | Out-File "$X64Version-sha256.txt"
          Get-FileHash $X86Version -Algorithm SHA256 | Select -expand Hash | Out-File "$X86Version-sha256.txt"
        workingDirectory: $(ARTIFACT_DOWNLOAD_DIRECTORY)
        displayName: 'Regenerate Windows Hash'

      - task: PublishBuildArtifacts@1
        displayName: 'Build Artifact: ReleaseBuilds'
        inputs:
          PathtoPublish: $(ARTIFACT_DOWNLOAD_DIRECTORY)
          ArtifactName: ReleaseBuilds

  - job: Sign_Mac_OS_Binary
    dependsOn: Build_All_Platforms
    pool:
      vmImage: macOS-11
      name: Azure Pipelines
      demands: xcode

    steps:
      - checkout: self
        clean: ${{ parameters.clean }}

      - task: DownloadPipelineArtifact@2
        displayName: 'Download Unsigned Builds'
        inputs:
          artifactName: 'ReleaseBuilds-Unsigned'
          targetPath: $(ARTIFACT_DOWNLOAD_DIRECTORY)

      - template: templates/task-go-install.yml
      - template: templates/task-go-detect-vendoring.yml
      - template: templates/task-go-restore-go-cache.yml
      - template: templates/task-go-mod-download.yml
      - template: templates/task-go-install-mage.yml

      - bash: |
          echo "---- GIT STATUS -----"
          echo $(git status)
          version=$(git describe --always --dirty --tags)
          echo "##vso[task.setvariable variable=CLI_VERSION]$version"
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        displayName: 'Get version'

      - task: InstallAppleCertificate@2
        displayName: 'Install Certificate to keychain'
        inputs:
          certSecureFile: '$(certSecureFile)'
          certPwd: '$(cert.password)'
          setUpPartitionIdACLForPrivateKey: false

      - bash: |
          echo $(CLI_VERSION)
          cd $(CLI_VERSION)
          ls
          ls $HOME/Library/Keychains

          #Clear unused files
          rm ./$(constants.cliname)-linux-x64
          rm ./$(constants.cliname)-linux-x64-sha256.txt
          rm ./$(constants.cliname)-linux-x86
          rm ./$(constants.cliname)-linux-x86-sha256.txt
          rm ./$(constants.cliname)-win-x64.exe
          rm ./$(constants.cliname)-win-x64.exe-sha256.txt
          rm ./$(constants.cliname)-win-x86.exe
          rm ./$(constants.cliname)-win-x86.exe-sha256.txt
          ls

          echo "[---] Signing x64 binary."
          codesign -s 'Thycotic Software' ./$(constants.cliname)-darwin-x64
          echo "[---] Signing arm64 binary."
          codesign -s 'Thycotic Software' ./$(constants.cliname)-darwin-arm64
          echo "[---] Finished."
        workingDirectory: $(ARTIFACT_DOWNLOAD_DIRECTORY)
        displayName: 'Sign macOS binaries'

      - bash: |
          brew install coreutils
          sudo ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum
          cd $(CLI_VERSION)
          sha256sum ./$(constants.cliname)-darwin-x64 > ./$(constants.cliname)-darwin-x64-sha256.txt
          sha256sum ./$(constants.cliname)-darwin-arm64 > ./$(constants.cliname)-darwin-arm64-sha256.txt
        workingDirectory: $(ARTIFACT_DOWNLOAD_DIRECTORY)
        displayName: 'Regenerate macOS Hash'

      - task: PublishBuildArtifacts@1
        displayName: 'Build Artifact: ReleaseBuilds'
        inputs:
          PathtoPublish: $(ARTIFACT_DOWNLOAD_DIRECTORY)
          ArtifactName: ReleaseBuilds
