// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"sync"
	"github.com/DelineaXPM/dsv-cli/auth"
	"github.com/DelineaXPM/dsv-cli/errors"
)

type FakeAuthenticator struct {
	GetTokenStub        func() (*auth.TokenResponse, *errors.ApiError)
	getTokenMutex       sync.RWMutex
	getTokenArgsForCall []struct {
	}
	getTokenReturns struct {
		result1 *auth.TokenResponse
		result2 *errors.ApiError
	}
	getTokenReturnsOnCall map[int]struct {
		result1 *auth.TokenResponse
		result2 *errors.ApiError
	}
	WipeCachedTokensStub        func() *errors.ApiError
	wipeCachedTokensMutex       sync.RWMutex
	wipeCachedTokensArgsForCall []struct {
	}
	wipeCachedTokensReturns struct {
		result1 *errors.ApiError
	}
	wipeCachedTokensReturnsOnCall map[int]struct {
		result1 *errors.ApiError
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAuthenticator) GetToken() (*auth.TokenResponse, *errors.ApiError) {
	fake.getTokenMutex.Lock()
	ret, specificReturn := fake.getTokenReturnsOnCall[len(fake.getTokenArgsForCall)]
	fake.getTokenArgsForCall = append(fake.getTokenArgsForCall, struct {
	}{})
	stub := fake.GetTokenStub
	fakeReturns := fake.getTokenReturns
	fake.recordInvocation("GetToken", []interface{}{})
	fake.getTokenMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAuthenticator) GetTokenCallCount() int {
	fake.getTokenMutex.RLock()
	defer fake.getTokenMutex.RUnlock()
	return len(fake.getTokenArgsForCall)
}

func (fake *FakeAuthenticator) GetTokenCalls(stub func() (*auth.TokenResponse, *errors.ApiError)) {
	fake.getTokenMutex.Lock()
	defer fake.getTokenMutex.Unlock()
	fake.GetTokenStub = stub
}

func (fake *FakeAuthenticator) GetTokenReturns(result1 *auth.TokenResponse, result2 *errors.ApiError) {
	fake.getTokenMutex.Lock()
	defer fake.getTokenMutex.Unlock()
	fake.GetTokenStub = nil
	fake.getTokenReturns = struct {
		result1 *auth.TokenResponse
		result2 *errors.ApiError
	}{result1, result2}
}

func (fake *FakeAuthenticator) GetTokenReturnsOnCall(i int, result1 *auth.TokenResponse, result2 *errors.ApiError) {
	fake.getTokenMutex.Lock()
	defer fake.getTokenMutex.Unlock()
	fake.GetTokenStub = nil
	if fake.getTokenReturnsOnCall == nil {
		fake.getTokenReturnsOnCall = make(map[int]struct {
			result1 *auth.TokenResponse
			result2 *errors.ApiError
		})
	}
	fake.getTokenReturnsOnCall[i] = struct {
		result1 *auth.TokenResponse
		result2 *errors.ApiError
	}{result1, result2}
}

func (fake *FakeAuthenticator) WipeCachedTokens() *errors.ApiError {
	fake.wipeCachedTokensMutex.Lock()
	ret, specificReturn := fake.wipeCachedTokensReturnsOnCall[len(fake.wipeCachedTokensArgsForCall)]
	fake.wipeCachedTokensArgsForCall = append(fake.wipeCachedTokensArgsForCall, struct {
	}{})
	stub := fake.WipeCachedTokensStub
	fakeReturns := fake.wipeCachedTokensReturns
	fake.recordInvocation("WipeCachedTokens", []interface{}{})
	fake.wipeCachedTokensMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthenticator) WipeCachedTokensCallCount() int {
	fake.wipeCachedTokensMutex.RLock()
	defer fake.wipeCachedTokensMutex.RUnlock()
	return len(fake.wipeCachedTokensArgsForCall)
}

func (fake *FakeAuthenticator) WipeCachedTokensCalls(stub func() *errors.ApiError) {
	fake.wipeCachedTokensMutex.Lock()
	defer fake.wipeCachedTokensMutex.Unlock()
	fake.WipeCachedTokensStub = stub
}

func (fake *FakeAuthenticator) WipeCachedTokensReturns(result1 *errors.ApiError) {
	fake.wipeCachedTokensMutex.Lock()
	defer fake.wipeCachedTokensMutex.Unlock()
	fake.WipeCachedTokensStub = nil
	fake.wipeCachedTokensReturns = struct {
		result1 *errors.ApiError
	}{result1}
}

func (fake *FakeAuthenticator) WipeCachedTokensReturnsOnCall(i int, result1 *errors.ApiError) {
	fake.wipeCachedTokensMutex.Lock()
	defer fake.wipeCachedTokensMutex.Unlock()
	fake.WipeCachedTokensStub = nil
	if fake.wipeCachedTokensReturnsOnCall == nil {
		fake.wipeCachedTokensReturnsOnCall = make(map[int]struct {
			result1 *errors.ApiError
		})
	}
	fake.wipeCachedTokensReturnsOnCall[i] = struct {
		result1 *errors.ApiError
	}{result1}
}

func (fake *FakeAuthenticator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getTokenMutex.RLock()
	defer fake.getTokenMutex.RUnlock()
	fake.wipeCachedTokensMutex.RLock()
	defer fake.wipeCachedTokensMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAuthenticator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ auth.Authenticator = new(FakeAuthenticator)
