---
name: scan
on:
  push:
    branches:
      - main
      - stable-*
  pull_request:
  workflow_dispatch:
  workflow_call: # so composite actions can use this
permissions:
  contents: read
jobs:
  scan:
    uses: delineaxpm/github-workflows/.github/workflows/scan.yml@main
    secrets: inherit
